name: Task
description: Generic task
title: "[Task]: "
type: 'Task'
projects: ["JakubMuzikOrg/2"]

body:
  - type: textarea
    id: task-spec
    attributes:
      label: Task specification
      placeholder: We need to..
    validations:
      required: false
