name: Bug
description: New Bug
title: "[Bug]: "
type: 'Bug'
projects: ["JakubMuzikOrg/2"]

body:

  - type: input
    id: bug-affected-products
    attributes:
      label: Affected product(s) and version(s)
      placeholder: "Affected product(s) and version(s)"
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Environment"
    validations:
      required: false
  
  - type: textarea
    id: bug-reproduced-result
    attributes:
      label: Steps to reproduce and current result
      placeholder: "Steps to reproduce, current result.."
    validations:
      required: false
   
  - type: textarea
    id: bug-expected-result
    attributes:
      label: Expected result / acceptance criteria
      placeholder: "Expected result, acceptance criteria.."
    validations:
      required: false
      
  - type: textarea
    id: log-output
    attributes:
      label: Log output
      placeholder: "Log snippets.."
    validations:
      required: false
      
  - type: textarea
    id: bug-qa-specification
    attributes:
      label: QA specification
      placeholder: "For BE tasks, please add: DB changes (table, column, …) and migration guidelines; Endpoint changes and migration guidelines; For FE/App tasks, please add build and App info."
    validations:
      required: false

  - type: input
    id: jira-issue-code
    attributes:
      label: JIRA issue code
      placeholder: "Add JIRA issue code as text"
    validations:
      required: false
