name: Dev working
description: New Dev task
title: "[Dev]: "
type: 'Dev'
projects: ["JakubMuzikOrg/2"]

body:

  - type: input
    id: products-versions
    attributes:
      label: Affected product(s) and version(s)
      placeholder: "Affected product(s) and version(s)"
    validations:
      required: false

  - type: input
    id: target-products-versions
    attributes:
      label: Target product(s) and version(s)
      placeholder: "Target product(s) and version(s)"
    validations:
      required: false
      
  - type: textarea
    id: specification
    attributes:
      label: Specification
      placeholder: Feature description, technical specification, attachments..
    validations:
      required: false

  - type: textarea
    id: qa-info
    attributes:
      label: QA info
      placeholder: "For BE tasks, please add: DB changes (table, column, …) and migration guidelines; Endpoint changes and migration guidelines; For FE/App tasks, please add build and App info."
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      placeholder: Add acceptance criteria..
    validations:
      required: false
