name: Dev working
description: New Dev task
title: "[Dev]: "
type: 'Dev'
projects: ["JakubMuzikOrg/2"]

body:

  - type: input
    id: products-versions
    attributes:
      label: Product(s) and version(s)
      placeholder: "Affected product(s) and version(s)"
    validations:
      required: false
      
  - type: textarea
    id: specification
    attributes:
      label: Specification
      placeholder: Feature description, technical specification..
    validations:
      required: false

  - type: textarea
    id: qa-info
    attributes:
      label: QA info
      value:
        App
        
        
        BE
        - [ ] DB changes
        Affected table, column, migration guideline
        - [ ] Endpoint changes
        Affected Endpoint, migration guideline
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      placeholder: Add acceptance criteria..
    validations:
      required: false
