name: Bug working
description: New Bug
title: "[Bug]: "
type: 'Bug'
projects: ["JakubMuzikOrg/2"]

body:

  - type: dropdown
    id: origin
    attributes:
      label: Origin
      options:
        - External bug
        - Internal bug
      validations:
      required: true

  - type: input
    id: products-versions
    attributes:
      label: Affected product(s) and version(s)
      placeholder: "Affected product(s) and version(s)"
    validations:
      required: false

  - type: input
    id: target-products-versions
    attributes:
      label: Target product(s) and version(s)
      placeholder: "Target product(s) and version(s)"
    validations:
      required: false
      
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Environment"
    validations:
      required: false
      
  - type: textarea
    id: qa-info
    attributes:
      label: Description
      value:
        Description, steps to reproduce
        
        
        
        
        App – App info and build

        
        BE – DB changes and migration guideline  

        
        BE – Endpoint changes and migration guideline

        
    validations:
      required: false
      
  - type: textarea
    id: log-output
    attributes:
      label: Log output
      placeholder: Add logs..
    validations:
      required: false
      
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      placeholder: Add acceptance criteria..
    validations:
      required: false
