name: Bug working
description: New Bug
title: "[Bug]: "
type: 'Bug'
projects: ["JakubMuzikOrg/2"]

body:

  - type: input
    id: product-version
    attributes:
      label: Affected product and version
      placeholder: "Affected product and version"
    validations:
      required: false
      
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "Environment"
    validations:
      required: false
      
  - type: textarea
    id: qa-info
    attributes:
      label: Description
      value:
        Description of the issue
        
        
        
        
        App – App info and build

        
        BE – DB changes and migration guideline  

        
        BE – Endpoint changes and migration guideline

        
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance criteria
      placeholder: Add acceptance criteria..
    validations:
      required: false
